ACTION_CATALOG = [
    "ANALYZE_COMPANY",
    "EXTRACT_SKILLS",
    "UPDATE_SKILL_MAP",
    "LEARN_PYTHON",
    "LEARN_DSA",
    "LEARN_AI",
    "LEARN_BACKEND",
    "BUILD_AI_PROJECT",
    "BUILD_BACKEND_PROJECT",
    "BUILD_FULLSTACK_PROJECT",
    "WRITE_TESTS",
    "TRACK_PROGRESS",
    "PUBLISH_GITHUB",
    "OPTIMIZE_RESUME",
    "APPLY_JOB",
    "PRACTICE_INTERVIEW",
    "REVIEW_FAILURE",
    "EXPLORE_HACKATHON",
    "GATHER_CERTIFICATION",
    "VALIDATE_READINESS",
]


SCENARIOS = [
    {
        "id": "S-101",
        "name": "AI Startup Hiring Sprint",
        "title": "AI Startup Hiring Sprint",
        "summary": "Target a product AI startup, strengthen the portfolio, and prove readiness before applying.",
        "target_company": "Product AI startup",
        "company_type": "product",
        "role": "ML engineer",
        "stage": "portfolio-first",
        "focus_modules": ["ANALYZE_COMPANY", "BUILD_AI_PROJECT", "WRITE_TESTS"],
        "required_skills": ["Python", "DSA", "LLM integration", "GitHub"],
        "skill_gaps": ["DSA", "deployment"],
        "initial_state": {
            "python": 70,
            "dsa": 42,
            "ai": 68,
            "backend": 38,
            "web": 45,
        },
        "projects": ["Placement intelligence demo"],
        "proof_targets": {
            "projects": 2,
            "dsa": 60,
            "resume": 25,
            "interview": 20,
            "branding": 20,
            "testing": 25,
            "readiness": 60,
        },
        "correct_action": "APPLY_JOB",
    },
    {
        "id": "S-102",
        "name": "Backend Service Role",
        "title": "Backend Service Role",
        "summary": "A backend-heavy role requires stronger testing, APIs, and system discipline.",
        "target_company": "Backend service company",
        "company_type": "service",
        "role": "backend engineer",
        "stage": "system-design",
        "focus_modules": ["LEARN_BACKEND", "BUILD_BACKEND_PROJECT", "WRITE_TESTS"],
        "required_skills": ["Python", "Backend APIs", "Testing", "Deployment"],
        "skill_gaps": ["backend", "testing"],
        "initial_state": {
            "python": 66,
            "dsa": 50,
            "ai": 40,
            "backend": 44,
            "web": 35,
        },
        "projects": ["Task tracker API"],
        "proof_targets": {
            "projects": 2,
            "dsa": 60,
            "resume": 25,
            "interview": 20,
            "branding": 20,
            "testing": 25,
            "readiness": 60,
        },
        "correct_action": "APPLY_JOB",
    },
    {
        "id": "S-103",
        "name": "Full Stack Internship",
        "title": "Full Stack Internship",
        "summary": "Build a visible full-stack portfolio and polish the resume before sending applications.",
        "target_company": "Product internship",
        "company_type": "product",
        "role": "full-stack intern",
        "stage": "resume",
        "focus_modules": ["BUILD_FULLSTACK_PROJECT", "PUBLISH_GITHUB", "OPTIMIZE_RESUME"],
        "required_skills": ["Python", "JavaScript", "GitHub", "Testing"],
        "skill_gaps": ["web", "branding"],
        "initial_state": {
            "python": 62,
            "dsa": 58,
            "ai": 34,
            "backend": 52,
            "web": 50,
        },
        "projects": ["Personal portfolio site"],
        "proof_targets": {
            "projects": 2,
            "dsa": 60,
            "resume": 25,
            "interview": 20,
            "branding": 20,
            "testing": 25,
            "readiness": 60,
        },
        "correct_action": "APPLY_JOB",
    },
    {
        "id": "S-104",
        "name": "Placement Recovery Mode",
        "title": "Placement Recovery Mode",
        "summary": "After a hackathon setback, the candidate needs feedback loops, weekly tracking, and proof-driven rebuilding.",
        "target_company": "Mixed placements",
        "company_type": "mixed",
        "role": "software engineer",
        "stage": "feedback",
        "focus_modules": ["REVIEW_FAILURE", "TRACK_PROGRESS", "PRACTICE_INTERVIEW"],
        "required_skills": ["Consistency", "DSA", "Resume", "Communication"],
        "skill_gaps": ["consistency", "communication"],
        "initial_state": {
            "python": 64,
            "dsa": 60,
            "ai": 48,
            "backend": 46,
            "web": 48,
        },
        "projects": ["Placement intelligence system", "OpenEnv validation harness"],
        "proof_targets": {
            "projects": 2,
            "dsa": 60,
            "resume": 25,
            "interview": 20,
            "branding": 20,
            "testing": 25,
            "readiness": 60,
        },
        "correct_action": "APPLY_JOB",
    },
    {
        "id": "S-105",
        "name": "Opportunity Explorer",
        "title": "Opportunity Explorer",
        "summary": "Explore new hackathons and niche openings while staying proof-based and selective.",
        "target_company": "Startup and hackathon pipeline",
        "company_type": "exploratory",
        "role": "generalist engineer",
        "stage": "opportunity",
        "focus_modules": ["EXPLORE_HACKATHON", "GATHER_CERTIFICATION", "APPLY_JOB"],
        "required_skills": ["Python", "DSA", "GitHub", "Interviewing"],
        "skill_gaps": ["brand", "applying"],
        "initial_state": {
            "python": 68,
            "dsa": 74,
            "ai": 55,
            "backend": 50,
            "web": 60,
        },
        "projects": ["OpenEnv placement intelligence simulator"],
        "proof_targets": {
            "projects": 2,
            "dsa": 60,
            "resume": 25,
            "interview": 20,
            "branding": 20,
            "testing": 25,
            "readiness": 60,
        },
        "correct_action": "APPLY_JOB",
    },
]
