ACTION_CATALOG = [
    "ASK_FOLLOWUP",
    "REQUEST_VITALS",
    "CHECK_MEDICATION_HISTORY",
    "SCHEDULE_TELEMEDICINE",
    "RECOMMEND_SELF_CARE",
    "RECOMMEND_DOCTOR_VISIT",
    "RECOMMEND_CLINIC",
    "ESCALATE_EMERGENCY",
]


SCENARIOS = [
    {
        "id": "C-101",
        "title": "Rural Cardiac Distress",
        "summary": "An elderly patient reports chest pain and breathlessness from a remote village.",
        "age_group": "elderly",
        "symptoms": ["chest_pain", "breathlessness", "fatigue"],
        "duration_days": 1,
        "severity": "critical",
        "rural_access": True,
        "mobility_issues": True,
        "chronic_conditions": ["hypertension"],
        "language_barrier": False,
        "insurance_risk": True,
        "red_flags": ["chest_pain", "breathlessness", "elderly"],
        "recommended_path": [
            "REQUEST_VITALS",
            "ESCALATE_EMERGENCY",
        ],
        "correct_action": "ESCALATE_EMERGENCY",
    },
    {
        "id": "C-102",
        "title": "Postpartum Fever Follow-up",
        "summary": "A new mother has fever, weakness, and increasing pain after recent delivery.",
        "age_group": "adult",
        "symptoms": ["fever", "pelvic_pain", "weakness"],
        "duration_days": 2,
        "severity": "high",
        "rural_access": False,
        "mobility_issues": False,
        "chronic_conditions": [],
        "language_barrier": True,
        "insurance_risk": False,
        "red_flags": ["postpartum", "fever", "pain"],
        "recommended_path": [
            "ASK_FOLLOWUP",
            "RECOMMEND_DOCTOR_VISIT",
        ],
        "correct_action": "RECOMMEND_DOCTOR_VISIT",
    },
    {
        "id": "C-103",
        "title": "Low-risk Viral Symptoms",
        "summary": "A young adult has mild fever, sore throat, and no breathing difficulty.",
        "age_group": "adult",
        "symptoms": ["mild_fever", "sore_throat", "runny_nose"],
        "duration_days": 3,
        "severity": "low",
        "rural_access": False,
        "mobility_issues": False,
        "chronic_conditions": [],
        "language_barrier": False,
        "insurance_risk": False,
        "red_flags": [],
        "recommended_path": [
            "ASK_FOLLOWUP",
            "RECOMMEND_SELF_CARE",
        ],
        "correct_action": "RECOMMEND_SELF_CARE",
    },
    {
        "id": "C-104",
        "title": "Diabetic Foot Infection",
        "summary": "A diabetic patient has swelling, wound discharge, and difficulty walking.",
        "age_group": "adult",
        "symptoms": ["foot_wound", "swelling", "pain"],
        "duration_days": 5,
        "severity": "high",
        "rural_access": True,
        "mobility_issues": True,
        "chronic_conditions": ["diabetes"],
        "language_barrier": False,
        "insurance_risk": True,
        "red_flags": ["wound", "diabetes", "mobility_limit"],
        "recommended_path": [
            "CHECK_MEDICATION_HISTORY",
            "RECOMMEND_CLINIC",
        ],
        "correct_action": "RECOMMEND_CLINIC",
    },
    {
        "id": "C-105",
        "title": "Child Asthma Review",
        "summary": "A child has wheezing episodes but is currently stable and has inhaler access.",
        "age_group": "child",
        "symptoms": ["wheezing", "cough"],
        "duration_days": 1,
        "severity": "moderate",
        "rural_access": False,
        "mobility_issues": False,
        "chronic_conditions": ["asthma"],
        "language_barrier": False,
        "insurance_risk": False,
        "red_flags": ["asthma_history"],
        "recommended_path": [
            "REQUEST_VITALS",
            "SCHEDULE_TELEMEDICINE",
        ],
        "correct_action": "SCHEDULE_TELEMEDICINE",
    },
]
